#!/usr/bin/env bash
# ============================================================================
# Turkey Food Supply Chain — one-shot local-stack bring-up
#
# Usage:
#   ./setup.sh            # bring up everything (idempotent)
#   ./setup.sh --clean    # wipe volumes first, then bring up (fresh state)
# ============================================================================

set -euo pipefail

cd "$(dirname "$0")"

# ---- .env: auto-generate on first run --------------------------------------
# HOST_IP / HOST_DNS are used by docker-compose to:
#   - whitelist NiFi's Host header (NIFI_WEB_PROXY_HOST)
#   - set Kafka's advertised listener for host-side clients
if [[ ! -f .env ]]; then
    # Best-effort: detect public IP; fall back to 127.0.0.1
    DETECTED_IP=$(curl -sf --max-time 3 ifconfig.me 2>/dev/null \
                  || curl -sf --max-time 3 ipinfo.io/ip 2>/dev/null \
                  || hostname -I 2>/dev/null | awk '{print $1}' \
                  || echo "localhost")
    cat > .env <<EOF
# Auto-generated by setup.sh — override if you want a different IP/DNS.
HOST_IP=${DETECTED_IP:-localhost}
HOST_DNS=localhost
EOF
    echo "[setup] generated .env with HOST_IP=${DETECTED_IP:-localhost}"
    echo "[setup]   (edit .env if you want a different IP / DNS name)"
fi

# shellcheck disable=SC1091
source .env
export HOST_IP HOST_DNS

# ---- pick docker compose vs docker-compose ---------------------------------
if docker compose version >/dev/null 2>&1; then
    DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
    DC="docker-compose"
else
    echo "[setup] ERROR: neither 'docker compose' nor 'docker-compose' found."
    echo "         Install Docker Desktop (Mac/Win) or 'sudo apt install docker.io docker-compose'."
    exit 1
fi

# ---- sudo prefix if needed -------------------------------------------------
if ! docker ps >/dev/null 2>&1; then
    if sudo -n docker ps >/dev/null 2>&1; then
        SUDO="sudo"
        echo "[setup] using sudo for docker (user not in docker group)"
    else
        echo "[setup] ERROR: cannot run docker. Either:"
        echo "         - add your user to the docker group: 'sudo usermod -aG docker \$USER' (then log out/in)"
        echo "         - or run this script with: 'sudo ./setup.sh'"
        exit 1
    fi
else
    SUDO=""
fi

# ---- optional clean slate --------------------------------------------------
if [[ "${1:-}" == "--clean" ]]; then
    echo "[setup] --clean: removing containers + volumes"
    $SUDO $DC down -v --remove-orphans || true
fi

# ---- pull + up -------------------------------------------------------------
echo "[setup] pulling images..."
$SUDO $DC pull --quiet

echo "[setup] starting stack..."
$SUDO $DC up -d

# ---- wait for healthy services --------------------------------------------
echo -n "[setup] waiting for kafka "
until $SUDO docker exec kafka kafka-broker-api-versions --bootstrap-server kafka:9092 >/dev/null 2>&1; do
    echo -n "."
    sleep 3
done
echo " OK"

echo -n "[setup] waiting for nifi "
until curl -sf -o /dev/null http://localhost:8080/nifi/ 2>/dev/null; do
    echo -n "."
    sleep 5
done
echo " OK"

# ---- build demo flow (GenerateFlowFile → PublishKafka → raw_market_prices) -
# Skips silently if the Python REST call fails (e.g. no python3 on the host) —
# users can still build the flow by hand from the NiFi UI.
if command -v python3 >/dev/null 2>&1; then
    echo "[setup] building live demo flow in NiFi (Gen → PublishKafka)..."
    python3 nifi_build_demo_flow.py || echo "[setup]   (demo-flow build skipped — build manually from UI)"
else
    echo "[setup] python3 not found — skipping demo-flow auto-build"
fi

# ---- show status -----------------------------------------------------------
echo
echo "============================================================"
echo " Stack ready — accessible from:"
echo "   NiFi        http://${HOST_IP}:8080/nifi"
echo "   Kafka UI    http://${HOST_IP}:8090"
echo "   MinIO       http://${HOST_IP}:9001   (admin / admin12345)"
echo "   Kafka       ${HOST_IP}:29092          (host-side / external)"
echo "   Kafka       kafka:9092                (inside docker net)"
echo "============================================================"
echo
echo " Kafka topics:"
$SUDO docker exec kafka kafka-topics --bootstrap-server kafka:9092 --list | sed 's/^/   - /'
echo
echo " NiFi demo flows (one per project data source) are live:"
echo "   market_demo_flow     → raw_market_prices   (every 2 s)"
echo "   hal_demo_flow        → raw_hal_prices      (every 5 s)"
echo "   weather_demo_flow    → raw_weather         (every 3 s)"
echo "   gdelt_demo_flow      → raw_gdelt           (every 4 s)"
echo "   epias_demo_flow      → raw_epias           (every 3 s)"
echo "   tcmb_demo_flow       → raw_tcmb            (every 6 s)"
echo "   akaryakit_demo_flow  → raw_akaryakit       (every 5 s)"
echo
echo " Open NiFi canvas — see all 7 process groups with live throughput:"
echo "   http://${HOST_IP}:8080/nifi"
echo
echo " Tail any topic to prove data is arriving:"
echo "   docker exec kafka kafka-console-consumer --bootstrap-server kafka:9092 \\"
echo "          --topic raw_market_prices --from-beginning --max-messages 5"
echo
echo " Stop the stack:  ./teardown.sh"
